import React from 'react'
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import second_section_image from '../../../Assets/Images/secondsection_image.webp'
import './Style.css'
import { BsFill1CircleFill, BsFill2CircleFill, BsFill3CircleFill, BsFill4CircleFill, BsFill5CircleFill } from "react-icons/bs";
import datalabimg1 from '../../../Assets/Images/datalabimg1.jpg';
import datalabimg2 from '../../../Assets/Images/datalabimg2.jpg';
import datalabimg3 from '../../../Assets/Images/datalabimg3.png';
import datalabimg4 from '../../../Assets/Images/datalabimg4.gif';
import datalabimg5 from '../../../Assets/Images/datalabimg5.jpeg';




function Datalabhome() {
  return (
    <>

        {/* top row */}
        <div className='datalab-colorwrap'>
          <Container className='py-4'>

            <Row>
              <Col md={7}>
                <h3 className='py-2'>Data to See Change and Make Better Decisions</h3>
                <p>Empowering Insights, Driving Change. Unleash the power of data with GeoMatrix, your ultimate destination for intelligent data solutions. With our cutting-edge cadastral mapping technology and user-friendly platform, you can visualize complex patterns effortlessly, gaining valuable insights to make informed decisions. Whether you're a professional, business owner, or data enthusiast, GeoMatrix offers tailored resources to support your journey towards progress. Join us today and transform your world with data-backed strategies, paving the way for a brighter future.</p>
              </Col>

              <Col md={5} className="d-flex justify-content-end">
                <img className='datalab-main-image' src={second_section_image} alt="second_section_image" />
              </Col>
            </Row>

            
          </Container>
        </div>

        <Container className='py-3'>
            <h3>How do we generate Data ?</h3>
        </Container>


        {/* step 1 */}
        <div>
            <Container className='py-5'>
                <Row>
                    <Col md={8}>
                        <Row>
                            <Col xs={2}> <BsFill1CircleFill style={{fontSize:'5rem', color:'skyblue'}}/> </Col>
                            <Col sx={10}>
                                <h3>Mapping cadastral data</h3>
                                <p>Geo matrix is mapping the cadastral data and keep tracking its changes. this is helpful to gov bodies to track the complex cadastral and provide better service to people with ease.</p>
                            </Col>
                        </Row>
                    </Col>
                    <Col md={4} className='datalabimgsize'>
                        <img src={datalabimg1} alt="datalabimgimg" />
                    </Col>

                </Row>
            </Container>
        </div>


        {/* step 2 */}
        <div>
            <Container className='py-5'>
                <Row>
                    
                    <Col md={4} className='datalabimgsize'>
                        <img src={datalabimg2} alt="datalabimgimg" />
                    </Col>
                    <Col md={8}>
                        <Row>
                            <Col sx={10}>
                                <h3>Keep tracking the updations</h3>
                                <p>Cadastral data updation such as land land registration, land ownership changing, taxing, land types and land uses makes the history of land data.</p>
                            </Col>
                            <Col xs={2}>
                                <BsFill2CircleFill style={{fontSize:'5rem', color:'skyblue'}} />
                            </Col>
                        </Row>
                    </Col>

                </Row>
            </Container>
        </div>


        {/* step 3 */}
        <div>
            <Container className='py-5'>
                <Row>
                    <Col md={8}>
                        <Row>
                            <Col xs={2}> <BsFill3CircleFill style={{fontSize:'5rem', color:'skyblue'}}/> </Col>
                            <Col sx={10}>
                                <h3>Generating cadastral Base map</h3>
                                <p>Cadastral data which is generated by different gov bodies and peoples are stored in the data base and constructing a Base map of the cadastral data which is the core of the Geo Matrix data Lab.</p>
                            </Col>
                        </Row>
                    </Col>
                    <Col md={4} className='datalabimgsize'>
                        <img src={datalabimg3} alt="datalabimgimg" />
                    </Col>

                </Row>
            </Container>
        </div>


        {/* step 4 */}
        <div>
            <Container className='py-5'>
                <Row>
                    
                    <Col md={4} className='datalabimgsize'>
                        <img src={datalabimg4} alt="datalabimgimg" />
                    </Col>
                    <Col md={8}>
                        <Row>
                            <Col sx={10}>
                                <h3>Layering</h3>
                                <p>Additional layers such as weather, elevations, road maps, etc.. added to the Base cadastral map to generate meaningful data</p>
                            </Col>
                            <Col xs={2}>
                                <BsFill4CircleFill style={{fontSize:'5rem', color:'skyblue'}} />
                            </Col>
                        </Row>
                    </Col>

                </Row>
            </Container>
        </div>


        {/* step 5 */}
        <div>
            <Container className='py-5'>
                <Row>
                    <Col md={8}>
                        <Row>
                            <Col xs={2}> <BsFill5CircleFill style={{fontSize:'5rem', color:'skyblue'}}/> </Col>
                            <Col sx={10}>
                                <h3>Data Lab data generation</h3>
                                <p>Cadastral base data and additional data layers produce more precise and meaningful real time data. this is can be used for different purpose cadastral insight, tax tracking, rescue operations, weather, economic insight, etc..</p>
                            </Col>
                        </Row>
                    </Col>
                    <Col md={4} className='datalabimgsize'>
                        <img src={datalabimg5} alt="datalabimgimg" />
                    </Col>

                </Row>
            </Container>
        </div>

    </>
  )
}

export default Datalabhome